app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("predictor.urls", namespace="predictor")),
    path("", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/predictor/urls.py
from django.urls import path

from . import views

app_name = "predictor"

urlpatterns = [
    path("", views.predict_stock, name="predict_stock"),
]

app/predictor/views.py
import requests
from bs4 import BeautifulSoup
import yfinance as yf
import pandas as pd
from sklearn.linear_model import LinearRegression
import numpy as np
from django.shortcuts import render


def fetch_stock_data(ticker):
    stock_data = yf.download(ticker, period="1y")

    stock_data.reset_index(inplace=True)

    historical_data = stock_data[["Date", "Close"]]
    return historical_data


def train_model(historical_data):
    historical_data["Date"] = pd.to_datetime(historical_data["Date"])
    historical_data["Date"] = historical_data["Date"].map(pd.Timestamp.timestamp)

    X = historical_data[["Date"]].values.reshape(-1, 1)
    y = historical_data["Close"].values

    model = LinearRegression().fit(X, y)
    return model


def predict_stock(request):
    ticker = None
    company_name = None
    predicted_price = None
    dates = []
    prices = []

    tickers = get_tickers()

    if request.method == "POST":
        ticker = request.POST.get("ticker").upper()

        historical_data = fetch_stock_data(ticker)

        if historical_data.empty:
            return render(
                request,
                "predictor/main.html",
                {"tickers": tickers, "error": "No data found for this ticker."},
            )

        company_name = get_full_company_name(ticker)

        dates = historical_data["Date"].dt.strftime("%Y-%m-%d").tolist()
        prices = historical_data["Close"].values.flatten().tolist()

        model = train_model(historical_data)
        future_date = np.array(
            [[pd.Timestamp.now().timestamp() + 86400]]
        )  # The next day: 86400 is 24h (24x60x60)
        predicted_price = model.predict(future_date)

        context = {
            "tickers": tickers,
            "ticker": ticker,
            "company_name": company_name,
            "dates": dates,
            "prices": prices,
            "predicted_price": predicted_price[0],
        }
        return render(request, "predictor/main.html", context)

    return render(
        request,
        "predictor/main.html",
        {
            "tickers": tickers,
        },
    )


def get_tickers():
    url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
    soup = BeautifulSoup(requests.get(url).text, "html.parser")
    table = soup.find("table", {"class": "wikitable"})

    tickers = []
    for row in table.find_all("tr")[1:]:
        ticker = row.find_all("td")[0].text.strip()
        tickers.append(ticker)

    return tickers


def get_full_company_name(ticker):
    stock = yf.Ticker(ticker)
    return stock.info.get("longName", "Unknown Company")

app/predictor/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:400,700&display=swap">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js" defer></script>
    
</head>

<body>

    <div id="content">
        {% block content %} {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js" defer></script>

</body>

</html>

app/predictor/templates/predictor/main.html
{% extends "base.html" %}

{% block title %}Stock Price Prediction{% endblock %}

{% block content %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<h2>Stock Price Prediction</h2>

<form method="post" action="{% url 'predictor:predict_stock' %}">
    {% csrf_token %}
    <div class="input-group mb-3">
        <label for="ticker">Select stock ticker:</label>
        <select id="ticker" name="ticker" class="form-control" required>
            <option value="" disabled selected>Select a ticker</option>
            {% for ticker in tickers %}
            <option value="{{ ticker }}" {% if ticker == selected_ticker %}selected{% endif %}>{{ ticker }}</option>
            {% endfor %}
        </select>
        <button type="submit" class="btn btn-info">Get prediction</button>
    </div>
</form>

<div class="main-with-chart">
{% if dates|length < 0 and prices|length < 0 %}

{% else %}
    <h3>{{ ticker }} ({{ company_name }}) stock price</h3>
    <p>Predicted price for tomorrow: {{ predicted_price|floatformat:2 }}</p>
    <div><canvas id="stockChart" width="400" height="200"></canvas></div>
    {% endif %}
</div>

    <script>
        
        document.addEventListener("DOMContentLoaded", function () {
            var ctx = document.getElementById('stockChart').getContext('2d');
            var stockChart = new Chart(ctx, {
                type: 'line',
                data: {
                    labels: {{ dates|safe }},
                    datasets: [{
                        label: 'Stock Price',
                        data: JSON.parse('{{ prices|safe|escapejs }}'), 
                        borderColor: 'rgba(75, 192, 192, 1)',
                        fill: false
                    }]
                },
                options: {
                    responsive: true,
                    scales: {
                        x: {
                            title: {
                                display: true,
                                text: 'Date'
                            }
                        },
                        y: {
                            title: {
                                display: true,
                                text: 'Price'
                            }
                        }
                    }
                }
            });
        });
    </script>
    

{% endblock %}